apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
spec:
  selector:
    matchLabels:
      app: project
  replicas: 4
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          image: tamerahmed1/petclinic-project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
